In [2]:
import awkward as ak
import pandas as pd
from datasets import load_dataset

dataset = load_dataset(
    "fastmachinelearning/collide-1m",
    data_dir="HH_bbWW",
    streaming=True,
)

ds = dataset["train"]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

Events can be:

- W → eν  → electrons present
- W → μν  → muons present
- W → τν  → maybe no reconstructed e/μ

In [3]:
cols = list(ds.features.keys())
for c in cols:
    print(c)

FullReco_PFCand_PT
FullReco_PFCand_Eta
FullReco_PFCand_Phi
FullReco_PFCand_PID
FullReco_PFCand_Charge
FullReco_PFCand_Mass
FullReco_PFCand_D0
FullReco_PFCand_DZ
FullReco_PFCand_ErrorD0
FullReco_PFCand_ErrorDZ
FullReco_PFCand_fUniqueID
FullReco_PFCand_PuppiW
FullReco_PUPPIPart_PT
FullReco_PUPPIPart_Eta
FullReco_PUPPIPart_Phi
FullReco_PUPPIPart_Charge
FullReco_PUPPIPart_Mass
FullReco_PUPPIPart_PID
FullReco_PUPPIPart_D0
FullReco_PUPPIPart_DZ
FullReco_PUPPIPart_ErrorD0
FullReco_PUPPIPart_ErrorDZ
FullReco_PUPPIPart_fUniqueID
FullReco_PUPPIPart_PuppiW
FullReco_Electron_PT
FullReco_Electron_Eta
FullReco_Electron_Phi
FullReco_Electron_EhadOverEem
FullReco_Electron_IsolationVarRhoCorr
FullReco_MuonTight_PT
FullReco_MuonTight_Eta
FullReco_MuonTight_Phi
FullReco_MuonTight_IsolationVarRhoCorr
FullReco_PhotonTight_PT
FullReco_PhotonTight_Eta
FullReco_PhotonTight_Phi
FullReco_JetAK4_PT
FullReco_JetAK4_Eta
FullReco_JetAK4_Phi
FullReco_JetAK4_Mass
FullReco_JetAK4_BTag
FullReco_JetAK4_BTagPhys
FullReco_JetAK4_Charge
FullReco_JetAK4_Constituents
FullReco_JetAK8_PT
FullReco_JetAK8_Eta
FullReco_JetAK8_Phi
FullReco_JetAK8_Mass
FullReco_JetAK8_BTag
FullReco_JetAK8_BTagPhys
FullReco_JetAK8_Charge
FullReco_JetAK8_Constituents
FullReco_JetPuppiAK4_PT
FullReco_JetPuppiAK4_Eta
FullReco_JetPuppiAK4_Phi
FullReco_JetPuppiAK4_Mass
FullReco_JetPuppiAK4_BTag
FullReco_JetPuppiAK4_BTagPhys
FullReco_JetPuppiAK4_Charge
FullReco_JetPuppiAK4_Constituents
FullReco_JetPuppiAK8_PT
FullReco_JetPuppiAK8_Eta
FullReco_JetPuppiAK8_Phi
FullReco_JetPuppiAK8_Mass
FullReco_JetPuppiAK8_BTag
FullReco_JetPuppiAK8_BTagPhys
FullReco_JetPuppiAK8_Charge
FullReco_JetPuppiAK8_Constituents
FullReco_MET_MET
FullReco_MET_Phi
FullReco_MET_Eta
FullReco_PUPPIMET_MET
FullReco_PUPPIMET_Phi
FullReco_PUPPIMET_Eta
FullReco_GenMissingET_MET
FullReco_GenMissingET_Eta
FullReco_GenMissingET_Phi
FullReco_GenPart_PT
FullReco_GenPart_Eta
FullReco_GenPart_Phi
FullReco_GenPart_PID
FullReco_GenPart_M1
FullReco_GenPart_M2
FullReco_GenPart_D1
FullReco_GenPart_D2
FullReco_GenPart_Status
FullReco_GenPart_IsPU
FullReco_GenJetAK4_PT
FullReco_GenJetAK4_Eta
FullReco_GenJetAK4_Phi
FullReco_GenJetAK4_Mass
FullReco_GenJetAK8_PT
FullReco_GenJetAK8_Eta
FullReco_GenJetAK8_Phi
FullReco_GenJetAK8_Mass
FullReco_PrimaryVertex_X
FullReco_PrimaryVertex_Y
FullReco_PrimaryVertex_Z
FullReco_PrimaryVertex_T
FullReco_PrimaryVertex_SumPT2
L1T_PFCand_PT
L1T_PFCand_Eta
L1T_PFCand_Phi
L1T_PFCand_PID
L1T_PFCand_Charge
L1T_PFCand_Mass
L1T_PFCand_D0
L1T_PFCand_DZ
L1T_PFCand_ErrorD0
L1T_PFCand_ErrorDZ
L1T_PFCand_fUniqueID
L1T_PFCand_PuppiW
L1T_PUPPIPart_PT
L1T_PUPPIPart_Eta
L1T_PUPPIPart_Phi
L1T_PUPPIPart_Charge
L1T_PUPPIPart_Mass
L1T_PUPPIPart_PID
L1T_PUPPIPart_D0
L1T_PUPPIPart_DZ
L1T_PUPPIPart_ErrorD0
L1T_PUPPIPart_ErrorDZ
L1T_PUPPIPart_fUniqueID
L1T_PUPPIPart_PuppiW
L1T_Electron_PT
L1T_Electron_Eta
L1T_Electron_Phi
L1T_Electron_EhadOverEem
L1T_Electron_IsolationVarRhoCorr
L1T_MuonTight_PT
L1T_MuonTight_Eta
L1T_MuonTight_Phi
L1T_MuonTight_IsolationVarRhoCorr
L1T_PhotonTight_PT
L1T_PhotonTight_Eta
L1T_PhotonTight_Phi
L1T_JetAK4_PT
L1T_JetAK4_Eta
L1T_JetAK4_Phi
L1T_JetAK4_Mass
L1T_JetAK4_BTag
L1T_JetAK4_BTagPhys
L1T_JetAK4_Charge
L1T_JetAK4_Constituents
L1T_JetAK8_PT
L1T_JetAK8_Eta
L1T_JetAK8_Phi
L1T_JetAK8_Mass
L1T_JetAK8_BTag
L1T_JetAK8_BTagPhys
L1T_JetAK8_Charge
L1T_JetAK8_Constituents
L1T_JetPuppiAK4_PT
L1T_JetPuppiAK4_Eta
L1T_JetPuppiAK4_Phi
L1T_JetPuppiAK4_Mass
L1T_JetPuppiAK4_BTag
L1T_JetPuppiAK4_BTagPhys
L1T_JetPuppiAK4_Charge
L1T_JetPuppiAK4_Constituents
L1T_JetPuppiAK8_PT
L1T_JetPuppiAK8_Eta
L1T_JetPuppiAK8_Phi
L1T_JetPuppiAK8_Mass
L1T_JetPuppiAK8_BTag
L1T_JetPuppiAK8_BTagPhys
L1T_JetPuppiAK8_Charge
L1T_JetPuppiAK8_Constituents
L1T_MET_MET
L1T_MET_Phi
L1T_MET_Eta
L1T_PUPPIMET_MET
L1T_PUPPIMET_Phi
L1T_PUPPIMET_Eta

One event

In [4]:
row = next(iter(ds))

In [5]:
print(row.keys())

dict_keys(['FullReco_PFCand_PT', 'FullReco_PFCand_Eta', 'FullReco_PFCand_Phi', 'FullReco_PFCand_PID', 'FullReco_PFCand_Charge', 'FullReco_PFCand_Mass', 'FullReco_PFCand_D0', 'FullReco_PFCand_DZ', 'FullReco_PFCand_ErrorD0', 'FullReco_PFCand_ErrorDZ', 'FullReco_PFCand_fUniqueID', 'FullReco_PFCand_PuppiW', 'FullReco_PUPPIPart_PT', 'FullReco_PUPPIPart_Eta', 'FullReco_PUPPIPart_Phi', 'FullReco_PUPPIPart_Charge', 'FullReco_PUPPIPart_Mass', 'FullReco_PUPPIPart_PID', 'FullReco_PUPPIPart_D0', 'FullReco_PUPPIPart_DZ', 'FullReco_PUPPIPart_ErrorD0', 'FullReco_PUPPIPart_ErrorDZ', 'FullReco_PUPPIPart_fUniqueID', 'FullReco_PUPPIPart_PuppiW', 'FullReco_Electron_PT', 'FullReco_Electron_Eta', 'FullReco_Electron_Phi', 'FullReco_Electron_EhadOverEem', 'FullReco_Electron_IsolationVarRhoCorr', 'FullReco_MuonTight_PT', 'FullReco_MuonTight_Eta', 'FullReco_MuonTight_Phi', 'FullReco_MuonTight_IsolationVarRhoCorr', 'FullReco_PhotonTight_PT', 'FullReco_PhotonTight_Eta', 'FullReco_PhotonTight_Phi', 'FullReco_JetAK4_PT', 'FullReco_JetAK4_Eta', 'FullReco_JetAK4_Phi', 'FullReco_JetAK4_Mass', 'FullReco_JetAK4_BTag', 'FullReco_JetAK4_BTagPhys', 'FullReco_JetAK4_Charge', 'FullReco_JetAK4_Constituents', 'FullReco_JetAK8_PT', 'FullReco_JetAK8_Eta', 'FullReco_JetAK8_Phi', 'FullReco_JetAK8_Mass', 'FullReco_JetAK8_BTag', 'FullReco_JetAK8_BTagPhys', 'FullReco_JetAK8_Charge', 'FullReco_JetAK8_Constituents', 'FullReco_JetPuppiAK4_PT', 'FullReco_JetPuppiAK4_Eta', 'FullReco_JetPuppiAK4_Phi', 'FullReco_JetPuppiAK4_Mass', 'FullReco_JetPuppiAK4_BTag', 'FullReco_JetPuppiAK4_BTagPhys', 'FullReco_JetPuppiAK4_Charge', 'FullReco_JetPuppiAK4_Constituents', 'FullReco_JetPuppiAK8_PT', 'FullReco_JetPuppiAK8_Eta', 'FullReco_JetPuppiAK8_Phi', 'FullReco_JetPuppiAK8_Mass', 'FullReco_JetPuppiAK8_BTag', 'FullReco_JetPuppiAK8_BTagPhys', 'FullReco_JetPuppiAK8_Charge', 'FullReco_JetPuppiAK8_Constituents', 'FullReco_MET_MET', 'FullReco_MET_Phi', 'FullReco_MET_Eta', 'FullReco_PUPPIMET_MET', 'FullReco_PUPPIMET_Phi', 'FullReco_PUPPIMET_Eta', 'FullReco_GenMissingET_MET', 'FullReco_GenMissingET_Eta', 'FullReco_GenMissingET_Phi', 'FullReco_GenPart_PT', 'FullReco_GenPart_Eta', 'FullReco_GenPart_Phi', 'FullReco_GenPart_PID', 'FullReco_GenPart_M1', 'FullReco_GenPart_M2', 'FullReco_GenPart_D1', 'FullReco_GenPart_D2', 'FullReco_GenPart_Status', 'FullReco_GenPart_IsPU', 'FullReco_GenJetAK4_PT', 'FullReco_GenJetAK4_Eta', 'FullReco_GenJetAK4_Phi', 'FullReco_GenJetAK4_Mass', 'FullReco_GenJetAK8_PT', 'FullReco_GenJetAK8_Eta', 'FullReco_GenJetAK8_Phi', 'FullReco_GenJetAK8_Mass', 'FullReco_PrimaryVertex_X', 'FullReco_PrimaryVertex_Y', 'FullReco_PrimaryVertex_Z', 'FullReco_PrimaryVertex_T', 'FullReco_PrimaryVertex_SumPT2', 'L1T_PFCand_PT', 'L1T_PFCand_Eta', 'L1T_PFCand_Phi', 'L1T_PFCand_PID', 'L1T_PFCand_Charge', 'L1T_PFCand_Mass', 'L1T_PFCand_D0', 'L1T_PFCand_DZ', 'L1T_PFCand_ErrorD0', 'L1T_PFCand_ErrorDZ', 'L1T_PFCand_fUniqueID', 'L1T_PFCand_PuppiW', 'L1T_PUPPIPart_PT', 'L1T_PUPPIPart_Eta', 'L1T_PUPPIPart_Phi', 'L1T_PUPPIPart_Charge', 'L1T_PUPPIPart_Mass', 'L1T_PUPPIPart_PID', 'L1T_PUPPIPart_D0', 'L1T_PUPPIPart_DZ', 'L1T_PUPPIPart_ErrorD0', 'L1T_PUPPIPart_ErrorDZ', 'L1T_PUPPIPart_fUniqueID', 'L1T_PUPPIPart_PuppiW', 'L1T_Electron_PT', 'L1T_Electron_Eta', 'L1T_Electron_Phi', 'L1T_Electron_EhadOverEem', 'L1T_Electron_IsolationVarRhoCorr', 'L1T_MuonTight_PT', 'L1T_MuonTight_Eta', 'L1T_MuonTight_Phi', 'L1T_MuonTight_IsolationVarRhoCorr', 'L1T_PhotonTight_PT', 'L1T_PhotonTight_Eta', 'L1T_PhotonTight_Phi', 'L1T_JetAK4_PT', 'L1T_JetAK4_Eta', 'L1T_JetAK4_Phi', 'L1T_JetAK4_Mass', 'L1T_JetAK4_BTag', 'L1T_JetAK4_BTagPhys', 'L1T_JetAK4_Charge', 'L1T_JetAK4_Constituents', 'L1T_JetAK8_PT', 'L1T_JetAK8_Eta', 'L1T_JetAK8_Phi', 'L1T_JetAK8_Mass', 'L1T_JetAK8_BTag', 'L1T_JetAK8_BTagPhys', 'L1T_JetAK8_Charge', 'L1T_JetAK8_Constituents', 'L1T_JetPuppiAK4_PT', 'L1T_JetPuppiAK4_Eta', 'L1T_JetPuppiAK4_Phi', 'L1T_JetPuppiAK4_Mass', 'L1T_JetPuppiAK4_BTag', 'L1T_JetPuppiAK4_BTagPhys', 'L1T_JetPuppiAK4_Charge', 'L1T_JetPuppiAK4_Constituents', 'L1T_JetPuppiAK8_PT', 'L1T_JetPuppiAK8_Eta', 'L1T_JetPuppiAK8_Phi', 'L1T_JetPuppiAK8_Mass', 'L1T_JetPuppiAK8_BTag', 'L1T_JetPuppiAK8_BTagPhys', 'L1T_JetPuppiAK8_Charge', 'L1T_JetPuppiAK8_Constituents', 'L1T_MET_MET', 'L1T_MET_Phi', 'L1T_MET_Eta', 'L1T_PUPPIMET_MET', 'L1T_PUPPIMET_Phi', 'L1T_PUPPIMET_Eta'])

Jets in Event

- btag        = detector-level tagger output (realistic, noisy)
- btag_phys   = truth-level / “ideal” flavor label (almost ground truth)

In [6]:
jets = pd.DataFrame({
    "pt": row["FullReco_JetAK4_PT"],
    "eta": row["FullReco_JetAK4_Eta"],
    "phi": row["FullReco_JetAK4_Phi"],
    "mass": row["FullReco_JetAK4_Mass"],
    "btag": row["FullReco_JetAK4_BTag"],
    "btag_phys": row["FullReco_JetAK4_BTagPhys"],
})

jets

           pt       eta       phi       mass  btag  btag_phys
0  121.062500  1.128906  2.121094  23.046875     0          0
1   55.468750 -1.033203 -0.452637  11.382812     0          0
2   31.031250  1.638672 -2.107422   4.300781     0          0
3   30.281250 -0.604492 -0.711426   3.111328     0          0
4   23.671875 -0.991699 -3.021484   5.347656     0          0
5   23.312500 -0.255371 -0.111145  -2.414062     0          0
6   17.093750  2.234375  0.960938   3.730469     0          0
7   15.867188 -1.690430  0.216797   3.216797     0          0

Leptons and MET

In [7]:
electrons = pd.DataFrame({
    "pt": row["FullReco_Electron_PT"],
    "eta": row["FullReco_Electron_Eta"],
    "phi": row["FullReco_Electron_Phi"],
})

muons = pd.DataFrame({
    "pt": row["FullReco_MuonTight_PT"],
    "eta": row["FullReco_MuonTight_Eta"],
    "phi": row["FullReco_MuonTight_Phi"],
})

print("MET:", row["FullReco_MET_MET"], "phi:", row["FullReco_MET_Phi"])

electrons, muons

MET: [65.875] phi: [-1.5107421875]

(Empty DataFrame
 Columns: [pt, eta, phi]
 Index: [],
 Empty DataFrame
 Columns: [pt, eta, phi]
 Index: [])

this event has NO electrons and NO muons

In [8]:
for row in ds:
    if len(row["FullReco_Electron_PT"]) + len(row["FullReco_MuonTight_PT"]) > 0:
        break

In [9]:
electrons = pd.DataFrame({
    "pt": row["FullReco_Electron_PT"],
    "eta": row["FullReco_Electron_Eta"],
    "phi": row["FullReco_Electron_Phi"],
})

muons = pd.DataFrame({
    "pt": row["FullReco_MuonTight_PT"],
    "eta": row["FullReco_MuonTight_Eta"],
    "phi": row["FullReco_MuonTight_Phi"],
})

electrons, muons

(          pt       eta       phi
 0  20.640625 -1.515625 -2.736328,
 Empty DataFrame
 Columns: [pt, eta, phi]
 Index: [])

PARTICLE-FLOW CANDIDATES

In [10]:
pfcands = pd.DataFrame({
    "pt": row["FullReco_PFCand_PT"],
    "eta": row["FullReco_PFCand_Eta"],
    "phi": row["FullReco_PFCand_Phi"],
    "pid": row["FullReco_PFCand_PID"],
    "charge": row["FullReco_PFCand_Charge"],
    "mass": row["FullReco_PFCand_Mass"],
})

pfcands.head(), len(pfcands)

(         pt       eta       phi  pid  charge      mass
 0  0.350342 -3.783203  0.747070  -45       1  0.139526
 1  2.736328 -3.492188 -2.117188   45      -1  0.139526
 2  0.758301 -3.578125 -0.679199   65       1  0.493652
 3  1.024414 -3.599609  0.760254   45      -1  0.139526
 4  1.177734 -3.533203  1.983398  -45       1  0.139526,
 4554)

Truth/gen particles

| pid | particle |
| --- | -------- |
| 5   | b quark  |
| -5  | anti-b   |
| 11  | electron |
| -11 | positron |
| 13  | muon     |
| 24  | W⁺       |
| -24 | W⁻       |
| 25  | Higgs    |

| status | meaning                            |
| ------ | ---------------------------------- |
| 1      | final state (stable, observable)   |
| 2–3    | intermediate                       |
| 22+    | hard process (generator dependent) |

In [11]:
gen = pd.DataFrame({
    "pt": row["FullReco_GenPart_PT"],  # transverse momentum
    "eta": row["FullReco_GenPart_Eta"], # pseudorapidity
    "phi": row["FullReco_GenPart_Phi"], # azimuthal angle
    "pid": row["FullReco_GenPart_PID"], # particle ID
    "m1": row["FullReco_GenPart_M1"], # index of mother 1
    "m2": row["FullReco_GenPart_M2"], # index of mother 2
    "d1": row["FullReco_GenPart_D1"], # index of daughter 1
    "d2": row["FullReco_GenPart_D2"], # index of daughter 2
    "status": row["FullReco_GenPart_Status"], # status code (1 for final state, 2 for intermediate, etc.)
})

gen.head(30)

           pt          eta       phi  pid   m1  m2    d1    d2  status
0    0.000000  1000.000000  0.000000   21    6  -1     3     5      21
1    0.000000 -1000.000000  0.000000   21    7  -1     3     5      21
2   35.250000    -2.880859  2.439453   25    0   2     9     9      22
3   17.734375    -1.392578 -0.192261   25    0   2    10    10      22
4   21.593750     0.833008 -1.116211   21    0   2    11    11      23
5   51.625000    -2.371094  2.498047   25    3  -1    15    15      44
6   45.687500    -0.335205  2.503906   25    4  -1    16    16      44
7   63.625000    -2.171875  2.509766   25    9  -1    25    25      44
8   48.781250    -0.318848  2.505859   25   10  -1    26    26      44
9   65.625000    -2.140625  2.589844   25   15  -1    41    41      44
10  49.281250    -0.313721  2.533203   25   16  -1    42    42      44
11  65.437500    -2.142578  2.582031   25   25  -1   702   702      44
12  48.750000    -0.312500  2.496094   25   26  -1   703   703      44
13   3.271484     1.460938  0.287109   -4   95  -1   341   341      51
14   2.996094     0.587891  1.769531    4   95  -1   121   121      51
15   2.830078     0.581543  1.769531    4  117  -1   343   343      52
16   2.695312     1.655273  0.398193   -4  116  -1   788   788      44
17   2.931641     0.547852  1.849609    4  121  -1   388   388      44
18   2.792969     0.541504  1.847656    4  343  -1   790   790      52
19  65.437500    -2.142578  2.587891   25   41  -1   894   895      62
20  48.687500    -0.312744  2.500000   25   42  -1   905   906      62
21   2.910156     1.576172  0.492432   -4  341  -1  1022  1022      62
22   2.898438     0.504395  1.830078    4  388  -1  1380  1380      62
23  67.062500    -1.399414  1.409180    5  702  -1   898   898      23
24  73.687500    -1.444336 -2.695312   -5  702  -1   896   897      23
25  73.437500    -1.452148 -2.693359   -5  895  -1   901   901      51
26  66.250000    -1.399414  1.409180    5  894  -1  1133  1133      52
27  70.937500    -1.452148 -2.693359   -5  896  -1  1030  1030      52
28  23.453125    -0.081726  2.841797  -24  703  -1   907   908      22
29  27.734375    -0.471191  2.212891   24  703  -1   948   949      22

One row = one event.
Objects available:
- AK4 jets
- AK8 jets
- PF candidates
- electrons/muons
- MET
- gen particles

For SPA-Net resolved case:
- candidate inputs = AK4 jets
- possible features = pt, eta, phi, mass, btag, btag_phys
- truth labels likely need gen-particle/gen-jet matching

##### one event → gen particles → true H→bb quarks → reconstructed jets → SPA-Net target labels

In [12]:
gen = pd.DataFrame({
    "idx": range(len(row["FullReco_GenPart_PT"])),
    "pt": row["FullReco_GenPart_PT"],
    "eta": row["FullReco_GenPart_Eta"],
    "phi": row["FullReco_GenPart_Phi"],
    "pid": row["FullReco_GenPart_PID"],
    "m1": row["FullReco_GenPart_M1"],
    "m2": row["FullReco_GenPart_M2"],
    "d1": row["FullReco_GenPart_D1"],
    "d2": row["FullReco_GenPart_D2"],
    "status": row["FullReco_GenPart_Status"],
})

gen = gen.set_index("idx", drop=False)

In [13]:
print("Number of GenParts:", len(gen))
print("Does 702 exist?", 702 in gen.index)

Number of GenParts: 401
Does 702 exist? False

Try to look for datasets with Higgs

Find Higgs bosons

In [14]:
gen[gen["pid"].abs() == 25]

     idx         pt       eta       phi  pid  m1  m2   d1   d2  status
idx
2      2  35.250000 -2.880859  2.439453   25   0   2    9    9      22
3      3  17.734375 -1.392578 -0.192261   25   0   2   10   10      22
5      5  51.625000 -2.371094  2.498047   25   3  -1   15   15      44
6      6  45.687500 -0.335205  2.503906   25   4  -1   16   16      44
7      7  63.625000 -2.171875  2.509766   25   9  -1   25   25      44
8      8  48.781250 -0.318848  2.505859   25  10  -1   26   26      44
9      9  65.625000 -2.140625  2.589844   25  15  -1   41   41      44
10    10  49.281250 -0.313721  2.533203   25  16  -1   42   42      44
11    11  65.437500 -2.142578  2.582031   25  25  -1  702  702      44
12    12  48.750000 -0.312500  2.496094   25  26  -1  703  703      44
19    19  65.437500 -2.142578  2.587891   25  41  -1  894  895      62
20    20  48.687500 -0.312744  2.500000   25  42  -1  905  906      62

In [15]:
gen[gen["pid"].abs() == 5]

     idx       pt       eta       phi  pid   m1  m2    d1    d2  status
idx
23    23  67.0625 -1.399414  1.409180    5  702  -1   898   898      23
24    24  73.6875 -1.444336 -2.695312   -5  702  -1   896   897      23
25    25  73.4375 -1.452148 -2.693359   -5  895  -1   901   901      51
26    26  66.2500 -1.399414  1.409180    5  894  -1  1133  1133      52
27    27  70.9375 -1.452148 -2.693359   -5  896  -1  1030  1030      52
43    43  70.9375 -1.452148 -2.693359   -5  901  -1  1031  1032      71
47    47  66.2500 -1.399414  1.409180    5  898  -1  1136  1141      71

In [16]:
# Find final-ish Higgs copies that decay into two distinct branches
higgs_final = gen[(gen["pid"].abs() == 25) & (gen["status"] == 62)]
higgs_final

     idx       pt       eta       phi  pid  m1  m2   d1   d2  status
idx
19    19  65.4375 -2.142578  2.587891   25  41  -1  894  895      62
20    20  48.6875 -0.312744  2.500000   25  42  -1  905  906      62

In [17]:
higgs_branch_ids = set(higgs_final["d1"].tolist() + higgs_final["d2"].tolist())

b_from_higgs = gen[
    (gen["pid"].abs() == 5)
    & (gen["m1"].isin(higgs_branch_ids))
]

b_from_higgs

     idx       pt       eta       phi  pid   m1  m2    d1    d2  status
idx
25    25  73.4375 -1.452148 -2.693359   -5  895  -1   901   901      51
26    26  66.2500 -1.399414  1.409180    5  894  -1  1133  1133      52

Then match those two b quarks to AK4 jets.

In [18]:
import numpy as np
import pandas as pd

def delta_phi(phi1, phi2):
    ''' computes the angular difference in phi, but correctly handles the wraparound at ±π.
    '''
    return np.arctan2(np.sin(phi1 - phi2), np.cos(phi1 - phi2))

def delta_r(eta1, phi1, eta2, phi2):
    '''ΔR = sqrt((Δη)^2 + (Δφ)^2)'''
    return np.sqrt((eta1 - eta2)**2 + delta_phi(phi1, phi2)**2)

# delta R to match a generator-level b quark to the nearest reconstructed AK4 jet.

jets = pd.DataFrame({
    "idx": range(len(row["FullReco_JetAK4_PT"])),
    "pt": row["FullReco_JetAK4_PT"],
    "eta": row["FullReco_JetAK4_Eta"],
    "phi": row["FullReco_JetAK4_Phi"],
    "mass": row["FullReco_JetAK4_Mass"],
    "btag": row["FullReco_JetAK4_BTag"],
    "btag_phys": row["FullReco_JetAK4_BTagPhys"],
})

matches = []

for _, b in b_from_higgs.iterrows():
    drs = delta_r(jets["eta"], jets["phi"], b["eta"], b["phi"])
    best = drs.idxmin()

    matches.append({
        "b_gen_idx": b["idx"],
        "b_pid": b["pid"],
        "b_pt": b["pt"],
        "b_eta": b["eta"],
        "b_phi": b["phi"],
        "matched_jet_idx": jets.loc[best, "idx"],
        "jet_pt": jets.loc[best, "pt"],
        "jet_eta": jets.loc[best, "eta"],
        "jet_phi": jets.loc[best, "phi"],
        "jet_btag": jets.loc[best, "btag"],
        "jet_btag_phys": jets.loc[best, "btag_phys"],
        "deltaR": drs.loc[best],
    })

matches = pd.DataFrame(matches)
matches

,b_gen_idx,b_pid,b_pt,b_eta,b_phi,matched_jet_idx,jet_pt,jet_eta,jet_phi,jet_btag,jet_btag_phys,deltaR
0,25.0,-5.0,73.4375,-1.452148,-2.693359,6,22.78125,-1.494141,-2.708984,0,0,0.044805
1,26.0,5.0,66.2500,-1.399414,1.409180,1,38.75000,-1.521484,1.541992,0,0,0.180389

check whether it is a usable SPA-Net training event:

In [19]:
usable = (
    len(matches) == 2
    and matches["matched_jet_idx"].nunique() == 2
    and (matches["deltaR"] < 0.4).all()
)

usable

np.True_

Now:
final Higgs status==62 → d1/d2 branch IDs → b quarks with m1 in those IDs

Later:
write a more general decay-tree parser if needed

event → H → bb truth → matched AK4 jet pair

Now, repeat this logic for one event in a function

In [20]:
def get_hbb_label(row, dr_cut=0.4):
    gen = pd.DataFrame({
        "idx": range(len(row["FullReco_GenPart_PT"])),
        "pt": row["FullReco_GenPart_PT"],
        "eta": row["FullReco_GenPart_Eta"],
        "phi": row["FullReco_GenPart_Phi"],
        "pid": row["FullReco_GenPart_PID"],
        "m1": row["FullReco_GenPart_M1"],
        "m2": row["FullReco_GenPart_M2"],
        "d1": row["FullReco_GenPart_D1"],
        "d2": row["FullReco_GenPart_D2"],
        "status": row["FullReco_GenPart_Status"],
    })

    jets = pd.DataFrame({
        "idx": range(len(row["FullReco_JetAK4_PT"])),
        "pt": row["FullReco_JetAK4_PT"],
        "eta": row["FullReco_JetAK4_Eta"],
        "phi": row["FullReco_JetAK4_Phi"],
        "mass": row["FullReco_JetAK4_Mass"],
        "btag": row["FullReco_JetAK4_BTag"],
        "btag_phys": row["FullReco_JetAK4_BTagPhys"],
    })

    if len(jets) < 2: # Require at least 2 jets for H -> bb
        return None

    # finds the Higgs bosons at the generator stage that seem to correspond to the useful final hard-process Higgs copies
    higgs_final = gen[(gen["pid"].abs() == 25) & (gen["status"] == 62)] 
    if len(higgs_final) == 0:
        return None

    # Get Higgs daughter branch IDs to find b quarks from Higgs decay
    higgs_branch_ids = set(higgs_final["d1"].tolist() + higgs_final["d2"].tolist())

    # Find b quarks from those Higgs branches
    b_from_higgs = gen[
        (gen["pid"].abs() == 5)
        & (gen["m1"].isin(higgs_branch_ids))
    ]

    if len(b_from_higgs) != 2:
        return None

    matched_jets = []

     # Match each b quark to the nearest jet and check if it's within the delta R cut
    for _, b in b_from_higgs.iterrows():
        drs = delta_r(jets["eta"], jets["phi"], b["eta"], b["phi"])
        best = drs.idxmin()

        # If the closest jet is too far away, then this event isn't a good H->bb candidate
        if drs.loc[best] > dr_cut:
            return None

        matched_jets.append(int(jets.loc[best, "idx"]))

    # rejects cases where both b quarks match to the same jet.
    if len(set(matched_jets)) != 2:
        return None

    return {
        "hbb_jets": matched_jets,
        "n_jets": len(jets),
        "jets": jets,
    }

Run for 100 events

In [21]:
n_seen = 0
n_usable = 0
examples = []

for row in ds:
    n_seen += 1
    label = get_hbb_label(row)

    if label is not None:
        n_usable += 1
        examples.append(label)

    if n_seen >= 100:
        break

print("seen:", n_seen)
print("usable:", n_usable)
print("usable fraction:", n_usable / n_seen)

seen: 100
usable: 72
usable fraction: 0.72

In [22]:
examples[0]["hbb_jets"], examples[0]["jets"]

([0, 2],
    idx          pt       eta       phi       mass  btag  btag_phys
 0    0  121.062500  1.128906  2.121094  23.046875     0          0
 1    1   55.468750 -1.033203 -0.452637  11.382812     0          0
 2    2   31.031250  1.638672 -2.107422   4.300781     0          0
 3    3   30.281250 -0.604492 -0.711426   3.111328     0          0
 4    4   23.671875 -0.991699 -3.021484   5.347656     0          0
 5    5   23.312500 -0.255371 -0.111145  -2.414062     0          0
 6    6   17.093750  2.234375  0.960938   3.730469     0          0
 7    7   15.867188 -1.690430  0.216797   3.216797     0          0)

Compare against the simple b-tag heuristic

In [23]:
label = examples[0]
jets = label["jets"]

top2_btag = jets.sort_values("btag", ascending=False)["idx"].head(2).tolist() # “pick the two most b-like jets”
truth = sorted(label["hbb_jets"])

print("truth:", truth)
print("top2 btag:", sorted(top2_btag))
print("correct:", sorted(top2_btag) == truth)

truth: [0, 2]
top2 btag: [0, 1]
correct: False

it got one correct (jet 0)
one wrong (jet 1 instead of jet 2)

In this dataset, standard b-tag-based heuristics are not effective for identifying H→bb jets, which motivates the use of learned representations and assignment models

##### To Answer: For HH→bbWW events, how often do the top-2 b-tagged AK4 jets match the true H→bb jets?

In [24]:
correct = 0
total = 0

for label in examples:
    jets = label["jets"]

    top2 = jets.sort_values("btag", ascending=False)["idx"].head(2).tolist()
    truth = sorted(label["hbb_jets"])

    if sorted(top2) == truth:
        correct += 1

    total += 1

print("accuracy:", correct / total)

accuracy: 0.4583333333333333

### Check for b-tags

In [25]:
all_btags = []

for label in examples:
    all_btags.extend(label["jets"]["btag"].tolist())

import numpy as np
print("unique btags:", np.unique(all_btags)[:20])
print("min/max:", np.min(all_btags), np.max(all_btags))
print("fraction nonzero:", np.mean(np.array(all_btags) > 0))

unique btags: [0 1]
min/max: 0 1
fraction nonzero: 0.15091463414634146

In [26]:
np.mean(all_btags), np.std(all_btags)

(np.float64(0.15091463414634146), np.float64(0.357965651071185))

In [27]:
for label in examples:
    if (label["jets"]["btag"] > 0).any():
        print("Found non-zero btag")
        break

Found non-zero btag

#### mass-pairing baseline
Pick the jet pair whose invariant mass is closest to 125 GeV.

In [28]:
import itertools
import numpy as np

def fourvec(pt, eta, phi, mass):
    px = pt * np.cos(phi)
    py = pt * np.sin(phi)
    pz = pt * np.sinh(eta)
    E = np.sqrt(px**2 + py**2 + pz**2 + mass**2)
    return E, px, py, pz

def dijet_mass(j1, j2):
    E1, px1, py1, pz1 = fourvec(j1.pt, j1.eta, j1.phi, j1.mass)
    E2, px2, py2, pz2 = fourvec(j2.pt, j2.eta, j2.phi, j2.mass)
    m2 = (E1+E2)**2 - (px1+px2)**2 - (py1+py2)**2 - (pz1+pz2)**2
    return np.sqrt(max(m2, 0))

def best_mass_pair(jets, target=125):
    best_pair = None
    best_score = float("inf")
    for i, j in itertools.combinations(jets.index, 2):
        m = dijet_mass(jets.loc[i], jets.loc[j])
        score = abs(m - target)
        if score < best_score:
            best_score = score
            best_pair = sorted([int(jets.loc[i, "idx"]), int(jets.loc[j, "idx"])])
    return best_pair

Compare b-tag to mass baseline

In [29]:
results = {"btag": 0, "mass": 0}
total = 0

for label in examples:
    jets = label["jets"]
    truth = sorted(label["hbb_jets"])

    pred_btag = sorted(jets.sort_values("btag", ascending=False)["idx"].head(2).tolist())
    pred_mass = best_mass_pair(jets)

    results["btag"] += pred_btag == truth
    results["mass"] += pred_mass == truth
    total += 1

print("total:", total)
print("btag accuracy:", results["btag"] / total)
print("mass accuracy:", results["mass"] / total)

total: 72
btag accuracy: 0.4583333333333333
mass accuracy: 0.1111111111111111

## Flavor information (b-tag) >> simple kinematics (mass)

But even flavor alone is not enough

Baseline performance:
- b-tag heuristic: ~46%
- mass pairing: ~11%

→ Need better methods for jet assignment

## Try: ΔR pairing
smallest ΔR between jets
because H → bb often produces relatively collimated jets

In [30]:
def best_dr_pair(jets):
    best_pair = None
    best_dr = float("inf")

    for i in range(len(jets)):
        for j in range(i+1, len(jets)):
            dr = delta_r(
                jets.loc[i, "eta"], jets.loc[i, "phi"],
                jets.loc[j, "eta"], jets.loc[j, "phi"]
            )
            if dr < best_dr:
                best_dr = dr
                best_pair = sorted([jets.loc[i, "idx"], jets.loc[j, "idx"]])

    return best_pair

In [31]:
# evaluate this DR-based pairing method as well
results["dr"] = 0
total = 0

for label in examples:
    jets = label["jets"]
    truth = sorted(label["hbb_jets"])

    pred_dr = best_dr_pair(jets)

    results["dr"] += pred_dr == truth
    total += 1

print("DR pairing accuracy:", results["dr"] / total)

DR pairing accuracy: 0.0

combined baseline next:

In [32]:
def best_btag_mass_pair(jets, target=125, alpha=50):
    best_pair = None
    best_score = float("inf")

    for i in range(len(jets)):
        for j in range(i + 1, len(jets)):
            m = dijet_mass(jets.loc[i], jets.loc[j])
            bsum = jets.loc[i, "btag"] + jets.loc[j, "btag"]
            score = abs(m - target) - alpha * bsum

            if score < best_score:
                best_score = score
                best_pair = sorted([int(jets.loc[i, "idx"]), int(jets.loc[j, "idx"])])

    return best_pair

In [33]:
correct = 0
total = 0

for label in examples:
    jets = label["jets"]
    truth = sorted(label["hbb_jets"])

    pred = best_btag_mass_pair(jets)
    correct += pred == truth
    total += 1

print("btag+mass accuracy:", correct / total)

btag+mass accuracy: 0.4444444444444444

### Compute per-event success breakdown

How often:
- perfect
- partially correct
- completely wrong

In [34]:
cases = {"both_correct": 0, "one_correct": 0, "none_correct": 0}

for label in examples:
    jets = label["jets"]
    truth = set(label["hbb_jets"])

    pred = set(jets.sort_values("btag", ascending=False)["idx"].head(2))

    overlap = len(pred & truth)

    if overlap == 2:
        cases["both_correct"] += 1
    elif overlap == 1:
        cases["one_correct"] += 1
    else:
        cases["none_correct"] += 1

print(cases)

{'both_correct': 33, 'one_correct': 37, 'none_correct': 2}

the correct jets are almost always among the top few candidates

model finds ONE correct b-jet, but fails to choose the SECOND one -> The problem is NOT “finding b-jets”

The problem IS “pairing them correctly”

Baseline analysis shows that b-tagging identifies candidate jets well,
but fails primarily in correctly pairing them.

This suggests that improvements should focus on modeling inter-jet relationships,
rather than improving per-jet classification alone.

Foundation model embeddings (e.g., ParT, GloParT, J-JEPA)
may provide richer representations to improve pairing performance.

In [35]:
print(jets.sort_values("btag", ascending=False))
print("truth:", label["hbb_jets"])

   idx         pt       eta       phi       mass  btag  btag_phys
2    2  70.937500 -1.364258 -2.841797  13.234375     1          0
5    5  31.375000 -0.841309  2.042969   4.027344     1          0
0    0  81.562500 -2.011719  0.010559   5.351562     0          0
1    1  75.437500 -0.483643  1.516602  18.046875     0          0
3    3  65.312500  0.198853 -1.448242   9.585938     0          0
4    4  45.312500 -0.562988 -2.291016   2.388672     0          0
6    6  29.203125 -3.337891 -2.255859   4.847656     0          0
7    7  19.031250 -4.437500 -0.509277   1.981445     0          0
truth: [0, 2]

btag is local → SPA-Net needs global reasoning

#### Question: Does pT help fix pairing?

In [36]:
def top2_pt(jets):
    return sorted(jets.sort_values("pt", ascending=False)["idx"].head(2).tolist())

In [37]:
correct = 0
total = 0

for label in examples:
    jets = label["jets"]
    truth = sorted(label["hbb_jets"])

    pred = top2_pt(jets)
    correct += pred == truth
    total += 1

print("pt accuracy:", correct / total)

pt accuracy: 0.1388888888888889

Picking the two highest-pT jets gives the correct H→bb pair only ~14% of the time. So pT alone is a weak reconstruction rule. The Higgs b-jets are not simply the two hardest jets in the event.

##### Restrict candidate jets

In [38]:
def top4_btag_then_mass(jets):
    jets_top = jets.sort_values("btag", ascending=False).head(4)

    return best_mass_pair(jets_top)

In [39]:
# evaluate 
correct = 0
total = 0

for label in examples:
    jets = label["jets"]
    truth = sorted(label["hbb_jets"])

    pred = top4_btag_then_mass(jets)
    correct += pred == truth
    total += 1

print("top4 btag then mass accuracy:", correct / total)

top4 btag then mass accuracy: 0.2638888888888889

If you first keep the top 4 btag jets, then choose the pair closest to 125 GeV, accuracy is ~26%.

btag ranking alone > btag preselection + mass pairing

#### Where is the truth jets ranked?

In [40]:
jets_sorted = jets.sort_values("btag", ascending=False)["idx"].tolist()

In [41]:
rank_truth = [jets_sorted.index(j) for j in truth]

In [ ]:
print("truth:", truth)
print("jets sorted by btag:", jets_sorted) 
print("rank of truth jets in btag sorting:", rank_truth)

truth: [0, 2]
jets sorted by btag: [2, 5, 0, 1, 3, 4, 6, 7]
rank of truth jets in btag sorting: [2, 0]

- true jet 2 is ranked 0th by btag → it is the highest-btag jet
- true jet 0 is ranked 2nd by btag → it is the third-highest btag jet
- the heuristic picked jets [2, 5]
- but truth was [0, 2]

So again: one correct jet is found, but the partner is wrong.

The true H→bb jets are often among high-btag candidates, but simple local rankings do not reliably identify the correct pair. The dominant failure is pairing/combinatorics, motivating SPA-Net or embedding-enhanced assignment models that can use inter-jet and event-level correlations.